Repository FuelLabs/sway-standards, pull requests merged in 2024-09, with the labels that each got.

#142 Fix Sway Standards inline docs
  CHANGELOG.md
  examples/src5-ownership/initialized_example/src/initialized_example.sw
  standards/src/src10.sw
  standards/src/src12.sw
  standards/src/src14.sw
  standards/src/src20.sw
  standards/src/src3.sw
  standards/src/src5.sw
  standards/src/src7.sw
Labels: Documentation

#147 Prepare for Sway-Standards `v0.6.1` release
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/src/index.md
Labels: Release

#149 Add helper functions to struct types and `Eq` implementations for all types
  CHANGELOG.md
  examples/src20-native-asset/multi_asset/src/multi_asset.sw
  examples/src20-native-asset/single_asset/src/single_asset.sw
  examples/src3-mint-burn/multi_asset/src/multi_asset.sw
  examples/src3-mint-burn/single_asset/src/single_asset.sw
  examples/src6-vault/multi_asset_vault/src/main.sw
  examples/src6-vault/single_asset_single_sub_vault/src/main.sw
  examples/src6-vault/single_asset_vault/src/main.sw
  examples/src7-metadata/multi_asset/src/multi_asset.sw
  examples/src7-metadata/single_asset/src/single_asset.sw
  standards/src/src10.sw
  standards/src/src11.sw
  standards/src/src20.sw
  standards/src/src5.sw
  standards/src/src6.sw
  standards/src/src7.sw
Labels: Enhancement, SRC 20, SRC 5, SRC-6, SRC-7, SRC-10, SRC-11

#150 Release v0.6.1
  .github/workflows/ci.yaml
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/spell-check-custom-words.txt
  docs/src/index.md
  docs/src/src-12-contract-factory.md
  docs/src/src-13-soulbound-address.md
  docs/src/src-14-simple-upgradeable-proxies.md
  docs/src/src-2-inline-documentation.md
  docs/src/src-5-ownership.md
  docs/src/src-6-vault.md
  docs/src/src-8-bridged-asset.md
  docs/src/src-9-metadata-keys.md
  examples/src14-simple-proxy/minimal/src/minimal.sw
  examples/src14-simple-proxy/owned/src/owned.sw
  examples/src20-native-asset/multi_asset/src/multi_asset.sw
  examples/src20-native-asset/single_asset/src/single_asset.sw
  examples/src3-mint-burn/multi_asset/src/multi_asset.sw
  examples/src3-mint-burn/single_asset/src/single_asset.sw
  examples/src5-ownership/initialized_example/src/initialized_example.sw
  examples/src5-ownership/uninitialized_example/src/uninitialized_example.sw
  examples/src6-vault/multi_asset_vault/src/main.sw
  examples/src6-vault/single_asset_single_sub_vault/src/main.sw
  examples/src6-vault/single_asset_vault/src/main.sw
  examples/src7-metadata/multi_asset/src/multi_asset.sw
  examples/src7-metadata/single_asset/src/single_asset.sw
  standards/src/src10.sw
  standards/src/src11.sw
  standards/src/src12.sw
  standards/src/src14.sw
  standards/src/src20.sw
  standards/src/src3.sw
  standards/src/src5.sw
  standards/src/src6.sw
  standards/src/src7.sw
Labels: Release

#151 Add required logging of SRC-20 to SRC-6 examples
  CHANGELOG.md
  examples/src6-vault/multi_asset_vault/src/main.sw
  examples/src6-vault/single_asset_single_sub_vault/src/main.sw
  examples/src6-vault/single_asset_vault/src/main.sw
Labels: Bug, Enhancement

#152 Add inline docs examples to SRC-6 abi
  CHANGELOG.md
  standards/src/src6.sw
Labels: Documentation

#153 Actually write to storage in src20 multi asset example
  CHANGELOG.md
  examples/src20-native-asset/multi_asset/src/multi_asset.sw
Labels: Bug
