Repository FuelLabs/sway-standards, pull requests merged in 2025-01, with the labels that each got.

#164 Release v0.6.2
  .github/workflows/ci.yaml
  .github/workflows/docs.yaml
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/spell-check-custom-words.txt
  docs/src/SUMMARY.md
  docs/src/index.md
  docs/src/src-15-offchain-asset-metadata.md
  docs/src/src-20-native-asset.md
  docs/src/src-3-minting-and-burning.md
  docs/src/src-7-asset-metadata.md
  examples/src15-offchain-metadata/Forc.toml
  examples/src15-offchain-metadata/multi_asset/Forc.toml
  examples/src15-offchain-metadata/multi_asset/src/multi_asset.sw
  examples/src15-offchain-metadata/single_asset/Forc.toml
  examples/src15-offchain-metadata/single_asset/src/single_asset.sw
  examples/src20-native-asset/multi_asset/src/multi_asset.sw
  examples/src6-vault/multi_asset_vault/src/main.sw
  examples/src6-vault/single_asset_single_sub_vault/src/main.sw
  examples/src6-vault/single_asset_vault/src/main.sw
  mlc_config.json
  standards/src/src15.sw
  standards/src/src6.sw
  standards/src/src7.sw
  standards/src/standards.sw
Labels: Release

#165 Add SRC-15 to README
  README.md
Labels: Documentation, SRC-15

#161 feat: add SRC-16 Typed Structured Data
  docs/spell-check-custom-words.txt
  docs/src/SUMMARY.md
  docs/src/index.md
  docs/src/src-16-typed-structured-data.md
  examples/src16-typed-data/Forc.toml
  examples/src16-typed-data/ethereum_example/Forc.toml
  examples/src16-typed-data/ethereum_example/src/main.sw
  examples/src16-typed-data/fuel_example/Forc.toml
  examples/src16-typed-data/fuel_example/src/main.sw
  standards/src/src16.sw
  standards/src/standards.sw
Labels: New Standard, cla:signed, SRC-16

#166 Update to use forc `v0.66.6` and fuel core `v0.40.0`
  .github/workflows/ci.yaml
  CHANGELOG.md
  README.md
  docs/src/index.md
  examples/src11-security-information/hardcoded-information/src/main.sw
  examples/src11-security-information/variable-information/src/main.sw
  examples/src12-contract-factory/with_configurables/src/utils.sw
  examples/src12-contract-factory/with_configurables/src/with_configurables.sw
  examples/src12-contract-factory/without_configurables/src/without_configurables.sw
  examples/src16-typed-data/Forc.toml
  examples/src16-typed-data/ethereum_example/Forc.toml
  examples/src16-typed-data/ethereum_example/src/main.sw
  examples/src16-typed-data/fuel_example/Forc.toml
  examples/src16-typed-data/fuel_example/src/main.sw
  examples/src20-native-asset/multi_asset/src/multi_asset.sw
  examples/src20-native-asset/single_asset/src/single_asset.sw
  standards/src/src16.sw
Labels: Repo Misc

#167 Prepare for v0.6.3 release
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/src/index.md
Labels: Repo Misc, Release

#168 Release v0.6.3
  .github/workflows/ci.yaml
  CHANGELOG.md
  README.md
  docs/spell-check-custom-words.txt
  docs/src/SUMMARY.md
  docs/src/index.md
  docs/src/src-16-typed-structured-data.md
  examples/src11-security-information/hardcoded-information/src/main.sw
  examples/src11-security-information/variable-information/src/main.sw
  examples/src12-contract-factory/with_configurables/src/utils.sw
  examples/src12-contract-factory/with_configurables/src/with_configurables.sw
  examples/src12-contract-factory/without_configurables/src/without_configurables.sw
  examples/src16-typed-data/Forc.toml
  examples/src16-typed-data/ethereum_example/Forc.toml
  examples/src16-typed-data/ethereum_example/src/main.sw
  examples/src16-typed-data/fuel_example/Forc.toml
  examples/src16-typed-data/fuel_example/src/main.sw
  examples/src20-native-asset/multi_asset/src/multi_asset.sw
  examples/src20-native-asset/single_asset/src/single_asset.sw
  standards/src/src16.sw
  standards/src/standards.sw
Labels: Release
